#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 15032bdb-9b94-4bfa-a423-31c6b31f0a9a
# Source File: C:\Users\kir9000\Documents\GitHub\PowerLauncher\PowerLauncher.psproj
#------------------------------------------------------------------------
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2014 v4.1.65
     Generated on:       9/9/2014 9:39 AM
     Generated by:       Kevin Kirkpatrick
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2014
#>


#region Source: Startup.pss
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
	Param ([String]$Commandline)
	#Note: This function starts the application
	#Note: $Commandline contains the complete argument string passed to the packager 
	#Note: To get the script directory in the Packager use: Split-Path $hostinvocation.MyCommand.path
	#Note: To get the console output in the Packager (Forms Mode) use: $ConsoleOutput (Type: System.Collections.ArrayList)
	#TODO: Initialize and add Function calls to forms
	
	if((Call-PowerLauncher_psf) -eq "OK")
	{
		
	}
	
	$global:ExitCode = 0 #Set the exit code for the Packager
}






#endregion Source: Startup.pss

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	$ConfigFilePath = "$env:allusersprofile\PowerLauncher\PowerLauncher_Config.ps1"
	
	. $ConfigFilePath
	
	$Log = "$env:allusersprofile\PowerLauncher\PowerLauncher.log"
	$AppVersion = "v1.0.0"
	
	function Test-ConfigFile
	{
		if (!(Test-Path $ConfigFilePath))
		{
			$lbstatus.forecolor = 'Red'
			$lbstatus.text = "Config File Not Found"
		} else
		{
			$lbstatus.text = $null
		}
	}
	
	function Load-ConfigFileVariables
	{
		$btnCustom1.Text = $CustomButton1_Text
		$btnCustom2.Text = $CustomButton2_Text
		$btnCustom3.Text = $CustomButton3_Text
		$btnCustom4.Text = $CustomButton4_Text
		$btnCustom5.Text = $CustomButton5_Text
		$btnCustom6.Text = $CustomButton6_Text
		$btnCustom7.Text = $CustomButton7_Text
		$btnCustom8.Text = $CustomButton8_Text
		$btnCustom9.Text = $CustomButton9_Text
		$btnCustom10.Text = $CustomButton10_Text
	}
	
	function Load-Buttons
	{
		if ($btnCustom1.Text -eq '') { $btnCustom1.Text = "Custom Button 1"; $btnCustom1.Enabled = $false }
		if ($btnCustom2.Text -eq '') { $btnCustom2.Text = "Custom Button 2"; $btnCustom2.Enabled = $false }
		if ($btnCustom3.Text -eq '') { $btnCustom3.Text = "Custom Button 3"; $btnCustom3.Enabled = $false }
		if ($btnCustom4.Text -eq '') { $btnCustom4.Text = "Custom Button 4"; $btnCustom4.Enabled = $false }
		if ($btnCustom5.Text -eq '') { $btnCustom5.Text = "Custom Button 5"; $btnCustom5.Enabled = $false }
		if ($btnCustom6.Text -eq '') { $btnCustom6.Text = "Custom Button 6"; $btnCustom6.Enabled = $false }
		if ($btnCustom7.Text -eq '') { $btnCustom7.Text = "Custom Button 7"; $btnCustom7.Enabled = $false }
		if ($btnCustom8.Text -eq '') { $btnCustom8.Text = "Custom Button 8"; $btnCustom8.Enabled = $false }
		if ($btnCustom9.Text -eq '') { $btnCustom9.Text = "Custom Button 9"; $btnCustom9.Enabled = $false }
		if ($btnCustom10.Text -eq '') { $btnCustom10.Text = "Custom Button 10"; $btnCustom10.Enabled = $false }
	}
	
	Function logstamp
	{
		#returns a padded timestamp string like 200705231132
		$now = Get-Date
		$yr = $now.Year.ToString()
		$mo = $now.Month.ToString()
		$dy = $now.Day.ToString()
		$hr = $now.Hour.ToString()
		$mi = $now.Minute.ToString()
		
		if ($mo.length -lt 2)
		{
			$mo = "0" + $mo #pad single digit months with leading zero
		}
		
		if ($dy.length -lt 2)
		{
			$dy = "0" + $dy #pad single digit day with leading zero
		}
		
		if ($hr.length -lt 2)
		{
			$hr = "0" + $hr #pad single digit hour with leading zero
		}
		
		if ($mi.length -lt 2)
		{
			$mi = "0" + $mi #pad single digit minute with leading zero
		}
		
		write-output $yr$mo$dy$hr$mi
	}
	
	function Disable-Buttons
	{
		$btnCustom1.Enabled = $false
		$btnCustom5.Enabled = $false
		$btnCustom3.Enabled = $false
		$btnCustom4.Enabled = $false
		$btnCustom2.Enabled = $false
		$btnCustom6.Enabled = $false
		$btnCustom7.Enabled = $false
		$btnCustom8.Enabled = $false
		$btnCustom9.Enabled = $false
		$btnCustom10.Enabled = $false
	}
	
	function Enable-Buttons
	{
		$btnCustom1.Enabled = $true
		$btnCustom2.Enabled = $true
		$btnCustom3.Enabled = $true
		$btnCustom4.Enabled = $true
		$btnCustom5.Enabled = $true
		$btnCustom6.Enabled = $true
		$btnCustom7.Enabled = $true
		$btnCustom8.Enabled = $true
		$btnCustom9.Enabled = $true
		$btnCustom10.Enabled = $false
	}
	
	function Clear-Formats
	{
		$lbStatus.Text = $null
	}
	#endregion Source: Globals.ps1

#region Source: PowerLauncher.psf
function Call-PowerLauncher_psf
{
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formPowerLauncher = New-Object 'System.Windows.Forms.Form'
	$lbVersion = New-Object 'System.Windows.Forms.Label'
	$btnCustom10 = New-Object 'System.Windows.Forms.Button'
	$btnCustom9 = New-Object 'System.Windows.Forms.Button'
	$btnCustom7 = New-Object 'System.Windows.Forms.Button'
	$btnCustom8 = New-Object 'System.Windows.Forms.Button'
	$btnCustom5 = New-Object 'System.Windows.Forms.Button'
	$btnCustom3 = New-Object 'System.Windows.Forms.Button'
	$btnCustom6 = New-Object 'System.Windows.Forms.Button'
	$btnCustom4 = New-Object 'System.Windows.Forms.Button'
	$btnCustom2 = New-Object 'System.Windows.Forms.Button'
	$lbStatus = New-Object 'System.Windows.Forms.Label'
	$btnCustom1 = New-Object 'System.Windows.Forms.Button'
	$menustrip1 = New-Object 'System.Windows.Forms.MenuStrip'
	$menuMenu = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuRestart = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuShutdown = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuExit = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuRefresh = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuTrouble = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuNetConnection = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuIP = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$aboutToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$tooltip1 = New-Object 'System.Windows.Forms.ToolTip'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	$formPowerLauncher_Load = {
		Test-ConfigFile
		Load-ConfigFileVariables
		Write-Output "[===== App Opened: $(logstamp) =====]" | Out-File $Log -Append
		Load-Buttons
		$lbVersion.Text = $AppVersion
	}
	
	$formPowerLauncher_Close = {
		Write-Output "[===== App Closed: $(logstamp) =====]" | Out-File $Log -Append
	}
	
	$btnCustom1_Click = { Start-Process -FilePath $CustomButton1_Script }
	$btnCustom2_Click = { Start-Process -FilePath $CustomButton2_Script }
	$btnCustom3_Click = { Start-Process -FilePath $CustomButton3_Script }
	$btnCustom4_Click = { Start-Process -FilePath $CustomButton4_Script }
	$btnCustom5_Click = { Start-Process -FilePath $CustomButton5_Script }
	$btnCustom6_Click = { Start-Process -FilePath $CustomButton6_Script }
	$btnCustom7_Click = { Start-Process -FilePath $CustomButton7_Script }
	$btnCustom8_Click = { Start-Process -FilePath $CustomButton8_Script }
	$btnCustom9_Click = { Start-Process -FilePath $CustomButton9_Script }
	$btnCustom10_Click= { Start-Process -FilePath $CustomButton10_Script }
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formPowerLauncher.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$btnCustom10.remove_Click($btnCustom10_Click)
			$btnCustom9.remove_Click($btnCustom9_Click)
			$btnCustom7.remove_Click($btnCustom7_Click)
			$btnCustom8.remove_Click($btnCustom8_Click)
			$btnCustom5.remove_Click($btnCustom5_Click)
			$btnCustom3.remove_Click($btnCustom3_Click)
			$btnCustom6.remove_Click($btnCustom6_Click)
			$btnCustom4.remove_Click($btnCustom4_Click)
			$btnCustom2.remove_Click($btnCustom2_Click)
			$btnCustom1.remove_Click($btnCustom1_Click)
			$formPowerLauncher.remove_FormClosed($formPowerLauncher_Close)
			$formPowerLauncher.remove_Load($formPowerLauncher_Load)
			$formPowerLauncher.remove_Load($Form_StateCorrection_Load)
			$formPowerLauncher.remove_Closing($Form_StoreValues_Closing)
			$formPowerLauncher.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formPowerLauncher.SuspendLayout()
	#
	# formPowerLauncher
	#
	$formPowerLauncher.Controls.Add($lbVersion)
	$formPowerLauncher.Controls.Add($btnCustom10)
	$formPowerLauncher.Controls.Add($btnCustom9)
	$formPowerLauncher.Controls.Add($btnCustom7)
	$formPowerLauncher.Controls.Add($btnCustom8)
	$formPowerLauncher.Controls.Add($btnCustom5)
	$formPowerLauncher.Controls.Add($btnCustom3)
	$formPowerLauncher.Controls.Add($btnCustom6)
	$formPowerLauncher.Controls.Add($btnCustom4)
	$formPowerLauncher.Controls.Add($btnCustom2)
	$formPowerLauncher.Controls.Add($lbStatus)
	$formPowerLauncher.Controls.Add($btnCustom1)
	$formPowerLauncher.Controls.Add($menustrip1)
	$formPowerLauncher.BackColor = 'White'
	$formPowerLauncher.ClientSize = '224, 582'
	$formPowerLauncher.FormBorderStyle = 'FixedDialog'
	#region Binary Data
	$formPowerLauncher.Icon = [System.Convert]::FromBase64String('
AAABAAIAICAAAAEAIACoEAAAJgAAAEBAAAABACAAKEIAAM4QAAAoAAAAIAAAAEAAAAABACAAAAAA
AIAQAAAAAAAAAAAAAAAAAAAAAAAAjEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+RTw//mFkc/5hZHP+YWRz/mFkc/5hZHP+YWRz/mFkc/5hZ
HP+YWRz/mFkc/5hZHP+SURH/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/xqSD
/59mLf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/8Shfv//////////////////////
/////////////////////////////////////82vkv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv/r39T//fz8/9jAqf+fZS3/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/xKF+////
////////////////////////////////////////////////////////za+S/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/+vf1P////////////39/P/XwKn/n2Ut/4xGAv+MRgL/
jEYC/4xGAv+vf1D/1Lqh/9S6of/UuqH/1Lqh/9S6of/UuqH/1Lqh/9S6of/UuqH/1Lqh/9S6of+1
iFz/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/2MCq//7+/v//////////////
///9/fz/18Cp/59lLf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
p3M//9/Muv/+/v3//////////////////f38/9jAqf+eYyr/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/6RuOP/cx7L//v38//////////////////38+//WvaX/nmMq
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+iaTL/2MGr//38+///
///////////////9/Pv/1r2l/55jK/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/n2Qs/9W8o//8+/r//////////////////fz7/9a9pf+eYyv/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5xgJv/Rtpz//Pr4//////////////////38
+//WvaX/nmMq/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+ZXCD/
zrGU//v49v/////////////////9+/r/1Lqh/5xhJ/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/l1gb/8usjv/+/f3//////////////////Pr5/5BODf+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+mcDv/5NXF//////////////////7+/v/l
1sf/jkoI/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+cYCX/2cGr//7+/f//////////
///////w59//tIZa/4xGA/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+UVBX/zK6Q//v6+P//
///////////////48+//wZx4/5BMCv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+PTAr/wJp1
//by7f/////////////////8+/r/z7OX/5ZWGP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RwT/tIZa/+/m3f/////////////////+/v7/3ci0/59lLP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/qHNA/+bXyP/+/v7/////////////////6dzQ/6t3Rv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/nWIo/9rFr//+/v7/////////////////8+zl/7iNZP+NSAX/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/lVUX/86xlP/8+/n/////////////////+vf0/8akgv+RTw7/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/o287//////////////////f38/9S6
oP+YWh3/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/+vf1P//////
/v7+/+HPvv+iajP/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/69/U/+zi1/+vf1D/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+wgFH/jkoI/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAEAAAACAAAAAAQAgAAAAAAAAQgAAAAAAAAAA
AAAAAAAAAAAAAIxGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+jbDb/pGw3/6RsN/+k
bDf/pGw3/6RsN/+kbDf/pGw3/6RsN/+kbDf/pGw3/6RsN/+kbDf/pGw3/6RsN/+kbDf/pGw3/6Rs
N/+kbDf/pGw3/6RsN/+kbDf/pGw3/6RsN/+PSwn/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/sIFS/5lcIP+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL//fz7////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////m18l
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/9jAqf/59vP/zbCT/5lbIP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC//38+///////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////5tfJf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/YwKn////////////5
9vP/zbCT/5lbH/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv/9/Pv/////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////+bXyX/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/2MCp///////////////////////69/T/za+S/5haHv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL//fz7////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////m18l/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/9jAqf//////////////
///////////////////69/T/za+T/5haHv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC//38+///////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////5tfJf+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv/YwKn////////////////////////////////////////////69/X/za+T
/5haHf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+pdUL/qnZE/6p2RP+qdkT/
qnZE/6p2RP+qdkT/qnZE/6p2RP+qdkT/qnZE/6p2RP+qdkT/qnZE/6p2RP+qdkT/qnZE/6p2RP+q
dkT/qnZE/6p2RP+qdkT/qnZE/6p2RP+QTAv/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/2MCp////////////////
///////////////////////////////////////6+Pb/zbCT/5haHv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/6dyP//i0cH//v39////////////////////////////////////////////
///////////6+PX/zbCT/5lbHv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/6h0Qf/fy7n/
/fz7///////////////////////////////////////////////////////69/T/zbCT/5lbH/+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/6VvOv/cx7P//fz6////////////////////////
///////////////////////////////69/T/yqqM/5dYG/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/6JqNP/Ywav//Pr5////////////////////////////////////////////////////
///49fH/yqqL/5dYG/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/6BmLv/VvKT/+/j2////
///////////////////////////////////////////////////49fH/yqqL/5dYG/+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/51iKf/St53/+fb0////////////////////////////////
///////////////////////49PD/yqqL/5dYHP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/5teI//Pspb/+PTw///////////////////////////////////////////////////////49PD/
yqqL/5dZHP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5hbHv/LrI7/9/Lu////////////
///////////////////////////////////////////48+//yqqL/5hZHP+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/5ZXGv/Ip4f/9fDr////////////////////////////////////////
///////////////48+//yqqL/5dZHP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5RUFf/F
oX//9O7o///////////////////////////////////////////////////////48+//yqqL/5dY
HP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5JQEf/Bm3f/8+zl////////////////////
///////////////////////////////////49PD/yqqL/5dYG/+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/5FODf+9lnD/8Ojg////////////////////////////////////////////////
///////38u7/xqSE/5VUFv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5BMCv+6kWj/7+Xc
///////////////////////////////////////////////////////38u7/xqSD/5RUFf+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/45KCP+2i2D/7OHW////////////////////////////
//////////////////////7+/v/18Ov/lFMV/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/41IBf+2il///Pr5/////////////////////////////////////////////fv6/5dYG/+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGA/+sekn/6dzP////////////////////////
//////////////////////////z7+v+XWBr/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/6FoMf/e
y7j//v7+/////////////////////////////////////////////v7+/+vg1f+ufU7/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/mVsf/9K3nv/9+/r/////////////////////////////////////////
////////9O3n/7yUbf+OSQf/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+SUBD/xqSD//n18v//////////////
///////////////////////////////////69/T/yamK/5RTFP+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/49L
Cf+6kGj/8uvk//////////////////////////////////////////////////38+//Xv6j/nGAl
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jUcE/659Tf/q3dH//v7+////////////////////////////////
/////////////v79/+PTw/+ncT3/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/o2w2/9/Muv/+/v7/////
////////////////////////////////////////////7uTa/7OFWP+NSAX/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+aXiP/1Lqh//z7+f/////////////////////////////////////////////////28Ov/
wJt2/5FODf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5RUFf/Ip4f/+PTx////////////////////////////
//////////////////////v49v/OsZT/llca/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/j0wK/7yTbP/z7OX/
/////////////////////////////////////////////////f38/9vFsP+fZS3/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+NSAT/sIFS/+vf1P/+/v7/////////////////////////////////////////////
////59nL/6p2Rf+MRwP/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+lbjn/4dC///79/f//////////////////
///////////////////////////////x6eH/t4xi/45JBv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5tfJP/W
vqf//fz7//////////////////////////////////////////////////j18f/EoX//kk8P/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/lFMU/8qqi//69/X/////////////////////////////////////////
/////////fz7/9K3nf+YWh7/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+PSwn/vpZw//Xv6f/+/v7/////////
///////////////////////////////////+/v7/4M27/6JpM/+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
A/+xglT/7uPa//7+/v/////////////////////////////////////////////////s4Nb/rn1N
/4xHA/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/Nr5L/////////////////////////////////////
/////////////v7+//Tu6P+7kmr/jkkH/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/2MCp
////////////////////////////////////////////+vf0/8moif+TURL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/9jAqf/////////////////////////////////9/Pv/
17+o/5teI/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/YwKn/
//////////////////////7+/f/j0sL/pnA8/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/2MCp/////////////////+7k2v+yhFf/jUcE/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/9jAqf//
////9fDr/8CZdf+QTQz/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/UuaD/zbCT/5ZXGv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/klAQ/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')
	#endregion
	$formPowerLauncher.MainMenuStrip = $menustrip1
	$formPowerLauncher.MaximizeBox = $False
	$formPowerLauncher.Name = "formPowerLauncher"
	$formPowerLauncher.StartPosition = 'CenterScreen'
	$formPowerLauncher.Text = "PowerLauncher"
	$formPowerLauncher.add_FormClosed($formPowerLauncher_Close)
	$formPowerLauncher.add_Load($formPowerLauncher_Load)
	#
	# lbVersion
	#
	$lbVersion.Font = "Gadugi, 6.75pt, style=Bold, Italic"
	$lbVersion.ForeColor = 'ControlDark'
	$lbVersion.Location = '163, 0'
	$lbVersion.Name = "lbVersion"
	$lbVersion.Size = '61, 18'
	$lbVersion.TabIndex = 10
	$lbVersion.Text = "lbVersion"
	$lbVersion.TextAlign = 'TopRight'
	#
	# btnCustom10
	#
	$btnCustom10.BackColor = 'ButtonFace'
	$btnCustom10.FlatAppearance.BorderColor = 'Gray'
	$btnCustom10.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom10.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom10.FlatStyle = 'Flat'
	$btnCustom10.Font = "Gadugi, 9.75pt"
	$btnCustom10.Location = '12, 498'
	$btnCustom10.Name = "btnCustom10"
	$btnCustom10.Size = '200, 47'
	$btnCustom10.TabIndex = 9
	$btnCustom10.Text = "Custom Button 10"
	$btnCustom10.UseVisualStyleBackColor = $False
	$btnCustom10.add_Click($btnCustom10_Click)
	#
	# btnCustom9
	#
	$btnCustom9.BackColor = 'ButtonFace'
	$btnCustom9.FlatAppearance.BorderColor = 'Gray'
	$btnCustom9.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom9.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom9.FlatStyle = 'Flat'
	$btnCustom9.Font = "Gadugi, 9.75pt"
	$btnCustom9.Location = '12, 445'
	$btnCustom9.Name = "btnCustom9"
	$btnCustom9.Size = '200, 47'
	$btnCustom9.TabIndex = 8
	$btnCustom9.Text = "Custom Button 9"
	$btnCustom9.UseVisualStyleBackColor = $False
	$btnCustom9.add_Click($btnCustom9_Click)
	#
	# btnCustom7
	#
	$btnCustom7.BackColor = 'ButtonFace'
	$btnCustom7.FlatAppearance.BorderColor = 'Gray'
	$btnCustom7.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom7.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom7.FlatStyle = 'Flat'
	$btnCustom7.Font = "Gadugi, 9.75pt"
	$btnCustom7.Location = '12, 339'
	$btnCustom7.Name = "btnCustom7"
	$btnCustom7.Size = '200, 47'
	$btnCustom7.TabIndex = 7
	$btnCustom7.Text = "Custom Button 7"
	$btnCustom7.UseVisualStyleBackColor = $False
	$btnCustom7.add_Click($btnCustom7_Click)
	#
	# btnCustom8
	#
	$btnCustom8.BackColor = 'ButtonFace'
	$btnCustom8.FlatAppearance.BorderColor = 'Gray'
	$btnCustom8.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom8.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom8.FlatStyle = 'Flat'
	$btnCustom8.Font = "Gadugi, 9.75pt"
	$btnCustom8.Location = '12, 392'
	$btnCustom8.Name = "btnCustom8"
	$btnCustom8.Size = '200, 47'
	$btnCustom8.TabIndex = 6
	$btnCustom8.Text = "Custom Button 8"
	$tooltip1.SetToolTip($btnCustom8, "Custom Button 7")
	$btnCustom8.UseVisualStyleBackColor = $False
	$btnCustom8.add_Click($btnCustom8_Click)
	#
	# btnCustom5
	#
	$btnCustom5.BackColor = 'ButtonFace'
	$btnCustom5.FlatAppearance.BorderColor = 'Gray'
	$btnCustom5.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom5.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom5.FlatStyle = 'Flat'
	$btnCustom5.Font = "Gadugi, 9.75pt"
	$btnCustom5.Location = '12, 233'
	$btnCustom5.Name = "btnCustom5"
	$btnCustom5.Size = '200, 47'
	$btnCustom5.TabIndex = 4
	$btnCustom5.Text = "Custom Button 5"
	$tooltip1.SetToolTip($btnCustom5, "Custom Button 5")
	$btnCustom5.UseVisualStyleBackColor = $False
	$btnCustom5.add_Click($btnCustom5_Click)
	#
	# btnCustom3
	#
	$btnCustom3.BackColor = 'ButtonFace'
	$btnCustom3.FlatAppearance.BorderColor = 'Gray'
	$btnCustom3.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom3.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom3.FlatStyle = 'Flat'
	$btnCustom3.Font = "Gadugi, 9.75pt"
	$btnCustom3.Location = '12, 127'
	$btnCustom3.Name = "btnCustom3"
	$btnCustom3.Size = '200, 47'
	$btnCustom3.TabIndex = 2
	$btnCustom3.Text = "Custom Button 3"
	$tooltip1.SetToolTip($btnCustom3, "Custom Button 3")
	$btnCustom3.UseVisualStyleBackColor = $False
	$btnCustom3.add_Click($btnCustom3_Click)
	#
	# btnCustom6
	#
	$btnCustom6.BackColor = 'ButtonFace'
	$btnCustom6.FlatAppearance.BorderColor = 'Gray'
	$btnCustom6.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom6.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom6.FlatStyle = 'Flat'
	$btnCustom6.Font = "Gadugi, 9.75pt"
	$btnCustom6.Location = '12, 286'
	$btnCustom6.Name = "btnCustom6"
	$btnCustom6.Size = '200, 47'
	$btnCustom6.TabIndex = 5
	$btnCustom6.Text = "Custom Button 6"
	$tooltip1.SetToolTip($btnCustom6, "Custom Button 6")
	$btnCustom6.UseVisualStyleBackColor = $False
	$btnCustom6.add_Click($btnCustom6_Click)
	#
	# btnCustom4
	#
	$btnCustom4.BackColor = 'ButtonFace'
	$btnCustom4.FlatAppearance.BorderColor = 'Gray'
	$btnCustom4.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom4.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom4.FlatStyle = 'Flat'
	$btnCustom4.Font = "Gadugi, 9.75pt"
	$btnCustom4.Location = '12, 180'
	$btnCustom4.Name = "btnCustom4"
	$btnCustom4.Size = '200, 47'
	$btnCustom4.TabIndex = 3
	$btnCustom4.Text = "Custom Button 4"
	$tooltip1.SetToolTip($btnCustom4, "Custom Button 4")
	$btnCustom4.UseVisualStyleBackColor = $False
	$btnCustom4.add_Click($btnCustom4_Click)
	#
	# btnCustom2
	#
	$btnCustom2.BackColor = 'ButtonFace'
	$btnCustom2.FlatAppearance.BorderColor = 'Gray'
	$btnCustom2.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom2.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom2.FlatStyle = 'Flat'
	$btnCustom2.Font = "Gadugi, 9.75pt"
	$btnCustom2.Location = '12, 74'
	$btnCustom2.Name = "btnCustom2"
	$btnCustom2.Size = '200, 47'
	$btnCustom2.TabIndex = 1
	$btnCustom2.Text = "Custom Button 2"
	$tooltip1.SetToolTip($btnCustom2, "Custom Button 2")
	$btnCustom2.UseVisualStyleBackColor = $False
	$btnCustom2.add_Click($btnCustom2_Click)
	#
	# lbStatus
	#
	$lbStatus.Font = "Gadugi, 9.75pt, style=Bold, Italic"
	$lbStatus.Location = '12, 548'
	$lbStatus.Name = "lbStatus"
	$lbStatus.Size = '200, 28'
	$lbStatus.TabIndex = 0
	$lbStatus.Text = "lbStatus"
	$lbStatus.TextAlign = 'MiddleCenter'
	#
	# btnCustom1
	#
	$btnCustom1.BackColor = 'ButtonFace'
	$btnCustom1.FlatAppearance.BorderColor = 'Gray'
	$btnCustom1.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom1.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom1.FlatStyle = 'Flat'
	$btnCustom1.Font = "Gadugi, 9.75pt"
	$btnCustom1.Location = '12, 21'
	$btnCustom1.Name = "btnCustom1"
	$btnCustom1.Size = '200, 47'
	$btnCustom1.TabIndex = 0
	$btnCustom1.Text = "Custom Button 1"
	$tooltip1.SetToolTip($btnCustom1, "Custom Button 1")
	$btnCustom1.UseVisualStyleBackColor = $False
	$btnCustom1.add_Click($btnCustom1_Click)
	#
	# menustrip1
	#
	[void]$menustrip1.Items.Add($menuMenu)
	[void]$menustrip1.Items.Add($menuRefresh)
	[void]$menustrip1.Items.Add($menuTrouble)
	$menustrip1.Location = '0, 0'
	$menustrip1.Name = "menustrip1"
	$menustrip1.Size = '427, 24'
	$menustrip1.TabIndex = 4
	$menustrip1.Text = "menustrip1"
	$menustrip1.Visible = $False
	#
	# menuMenu
	#
	[void]$menuMenu.DropDownItems.Add($menuRestart)
	[void]$menuMenu.DropDownItems.Add($menuShutdown)
	[void]$menuMenu.DropDownItems.Add($aboutToolStripMenuItem)
	[void]$menuMenu.DropDownItems.Add($menuExit)
	$menuMenu.Name = "menuMenu"
	$menuMenu.Size = '50, 20'
	$menuMenu.Text = "&Menu"
	#
	# menuRestart
	#
	$menuRestart.Name = "menuRestart"
	$menuRestart.Size = '185, 22'
	$menuRestart.Text = "&Restart Computer"
	#
	# menuShutdown
	#
	$menuShutdown.Name = "menuShutdown"
	$menuShutdown.Size = '185, 22'
	$menuShutdown.Text = "&Shutdown Computer"
	#
	# menuExit
	#
	$menuExit.Name = "menuExit"
	$menuExit.Size = '185, 22'
	$menuExit.Text = "&Exit"
	#
	# menuRefresh
	#
	$menuRefresh.Name = "menuRefresh"
	$menuRefresh.Size = '117, 20'
	$menuRefresh.Text = "&Check Connection"
	#
	# menuTrouble
	#
	[void]$menuTrouble.DropDownItems.Add($menuNetConnection)
	[void]$menuTrouble.DropDownItems.Add($menuIP)
	$menuTrouble.Name = "menuTrouble"
	$menuTrouble.Size = '90, 20'
	$menuTrouble.Text = "&Troubleshoot"
	#
	# menuNetConnection
	#
	$menuNetConnection.Name = "menuNetConnection"
	$menuNetConnection.Size = '184, 22'
	$menuNetConnection.Text = "Network Connection"
	#
	# menuIP
	#
	$menuIP.Name = "menuIP"
	$menuIP.Size = '184, 22'
	$menuIP.Text = "Show IP Address"
	#
	# aboutToolStripMenuItem
	#
	$aboutToolStripMenuItem.Name = "aboutToolStripMenuItem"
	$aboutToolStripMenuItem.Size = '185, 22'
	$aboutToolStripMenuItem.Text = "About"
	#
	# tooltip1
	#
	$formPowerLauncher.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formPowerLauncher.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formPowerLauncher.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formPowerLauncher.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formPowerLauncher.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formPowerLauncher.ShowDialog()
}
#endregion Source: PowerLauncher.psf

#Start the application
Main ($CommandLine)
