#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 15032bdb-9b94-4bfa-a423-31c6b31f0a9a
# Source File: C:\Users\kir9000\Documents\GitHub\PowerLauncher\PowerLauncher.psproj
#------------------------------------------------------------------------
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2014 v4.1.65
     Generated on:       9/10/2014 2:20 PM
     Generated by:       Kevin Kirkpatrick
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2014
#>


#region Source: Startup.pss
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
	Param ([String]$Commandline)
	#Note: This function starts the application
	#Note: $Commandline contains the complete argument string passed to the packager 
	#Note: To get the script directory in the Packager use: Split-Path $hostinvocation.MyCommand.path
	#Note: To get the console output in the Packager (Forms Mode) use: $ConsoleOutput (Type: System.Collections.ArrayList)
	#TODO: Initialize and add Function calls to forms
	
	if((Call-PowerLauncher_psf) -eq "OK")
	{
		
	}
	
	$global:ExitCode = 0 #Set the exit code for the Packager
}






#endregion Source: Startup.pss

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions
	#--------------------------------------------
	
	#region Declare Functions
	function Tab-Title
	{
		if (($tabPage1Title -eq "") -or ($tabPage1Title -eq $null))
		{
			$tabPg1.Text = "Page 1"
		} else
		{
			$tabPg1.Text = $tabPage1Title
		}
		
		if (($tabPage2Title -eq "") -or ($tabPage2Title -eq $null))
		{
			$tabPg2.Text = "Page 2"
		} else
		{
			$tabPg2.Text = $tabPage2Title
		}
	}# end function Tab-Title
	
	function Get-ScriptDirectory
	{
		if ($hostinvocation -ne $null)
		{
			Split-Path $hostinvocation.MyCommand.path
		} else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	function Load-ConfigFileVariables
	{
		$btnCustom1.Text = $CustomButton1_Text
		$btnCustom2.Text = $CustomButton2_Text
		$btnCustom3.Text = $CustomButton3_Text
		$btnCustom4.Text = $CustomButton4_Text
		$btnCustom5.Text = $CustomButton5_Text
		$btnCustom6.Text = $CustomButton6_Text
		$btnCustom7.Text = $CustomButton7_Text
		$btnCustom8.Text = $CustomButton8_Text
		$btnCustom9.Text = $CustomButton9_Text
		$btnCustom10.Text = $CustomButton10_Text
		$btnCustom11.Text = $CustomButton11_Text
		$btnCustom12.Text = $CustomButton12_Text
		$btnCustom13.Text = $CustomButton13_Text
		$btnCustom14.Text = $CustomButton14_Text
		$btnCustom15.Text = $CustomButton15_Text
		$btnCustom16.Text = $CustomButton16_Text
		$btnCustom17.Text = $CustomButton17_Text
		$btnCustom18.Text = $CustomButton18_Text
		$btnCustom19.Text = $CustomButton19_Text
		$btnCustom20.Text = $CustomButton20_Text
		
		
	}
	
	function Load-Buttons
	{
		if ($btnCustom1.Text -eq '') { $btnCustom1.Text = "Custom Button 1"; $btnCustom1.Enabled = $false }
		if ($btnCustom2.Text -eq '') { $btnCustom2.Text = "Custom Button 2"; $btnCustom2.Enabled = $false }
		if ($btnCustom3.Text -eq '') { $btnCustom3.Text = "Custom Button 3"; $btnCustom3.Enabled = $false }
		if ($btnCustom4.Text -eq '') { $btnCustom4.Text = "Custom Button 4"; $btnCustom4.Enabled = $false }
		if ($btnCustom5.Text -eq '') { $btnCustom5.Text = "Custom Button 5"; $btnCustom5.Enabled = $false }
		if ($btnCustom6.Text -eq '') { $btnCustom6.Text = "Custom Button 6"; $btnCustom6.Enabled = $false }
		if ($btnCustom7.Text -eq '') { $btnCustom7.Text = "Custom Button 7"; $btnCustom7.Enabled = $false }
		if ($btnCustom8.Text -eq '') { $btnCustom8.Text = "Custom Button 8"; $btnCustom8.Enabled = $false }
		if ($btnCustom9.Text -eq '') { $btnCustom9.Text = "Custom Button 9"; $btnCustom9.Enabled = $false }
		if ($btnCustom10.Text -eq '') { $btnCustom10.Text = "Custom Button 10"; $btnCustom10.Enabled = $false }
		if ($btnCustom11.Text -eq '') { $btnCustom11.Text = "Custom Button 11"; $btnCustom11.Enabled = $false }
		if ($btnCustom12.Text -eq '') { $btnCustom12.Text = "Custom Button 12"; $btnCustom12.Enabled = $false }
		if ($btnCustom13.Text -eq '') { $btnCustom13.Text = "Custom Button 13"; $btnCustom13.Enabled = $false }
		if ($btnCustom14.Text -eq '') { $btnCustom14.Text = "Custom Button 14"; $btnCustom14.Enabled = $false }
		if ($btnCustom15.Text -eq '') { $btnCustom15.Text = "Custom Button 15"; $btnCustom15.Enabled = $false }
		if ($btnCustom16.Text -eq '') { $btnCustom16.Text = "Custom Button 16"; $btnCustom16.Enabled = $false }
		if ($btnCustom17.Text -eq '') { $btnCustom17.Text = "Custom Button 17"; $btnCustom17.Enabled = $false }
		if ($btnCustom18.Text -eq '') { $btnCustom18.Text = "Custom Button 18"; $btnCustom18.Enabled = $false }
		if ($btnCustom19.Text -eq '') { $btnCustom19.Text = "Custom Button 19"; $btnCustom19.Enabled = $false }
		if ($btnCustom20.Text -eq '') { $btnCustom20.Text = "Custom Button 20"; $btnCustom20.Enabled = $false }
		
	}
	
	function logstamp
	{
		#returns a padded timestamp string like 200705231132
		$now = Get-Date
		$yr = $now.Year.ToString()
		$mo = $now.Month.ToString()
		$dy = $now.Day.ToString()
		$hr = $now.Hour.ToString()
		$mi = $now.Minute.ToString()
		
		if ($mo.length -lt 2)
		{
			$mo = "0" + $mo #pad single digit months with leading zero
		}
		
		if ($dy.length -lt 2)
		{
			$dy = "0" + $dy #pad single digit day with leading zero
		}
		
		if ($hr.length -lt 2)
		{
			$hr = "0" + $hr #pad single digit hour with leading zero
		}
		
		if ($mi.length -lt 2)
		{
			$mi = "0" + $mi #pad single digit minute with leading zero
		}
		
		write-output $yr$mo$dy$hr$mi
	}
	
	function Disable-Buttons
	{
		$btnCustom1.Enabled = $false
		$btnCustom2.Enabled = $false
		$btnCustom3.Enabled = $false
		$btnCustom4.Enabled = $false
		$btnCustom5.Enabled = $false
		$btnCustom6.Enabled = $false
		$btnCustom7.Enabled = $false
		$btnCustom8.Enabled = $false
		$btnCustom9.Enabled = $false
		$btnCustom10.Enabled = $false
		$btnCustom11.Enabled = $false
		$btnCustom12.Enabled = $false
		$btnCustom13.Enabled = $false
		$btnCustom14.Enabled = $false
		$btnCustom15.Enabled = $false
		$btnCustom16.Enabled = $false
		$btnCustom17.Enabled = $false
		$btnCustom18.Enabled = $false
		$btnCustom19.Enabled = $false
		$btnCustom20.Enabled = $false
	}
	
	function Enable-Buttons
	{
		$btnCustom1.Enabled = $true
		$btnCustom2.Enabled = $true
		$btnCustom3.Enabled = $true
		$btnCustom4.Enabled = $true
		$btnCustom5.Enabled = $true
		$btnCustom6.Enabled = $true
		$btnCustom7.Enabled = $true
		$btnCustom8.Enabled = $true
		$btnCustom9.Enabled = $true
		$btnCustom10.Enabled = $true
		$btnCustom11.Enabled = $true
		$btnCustom12.Enabled = $true
		$btnCustom13.Enabled = $true
		$btnCustom14.Enabled = $true
		$btnCustom15.Enabled = $true
		$btnCustom16.Enabled = $true
		$btnCustom17.Enabled = $true
		$btnCustom18.Enabled = $true
		$btnCustom19.Enabled = $true
		$btnCustom20.Enabled = $true
	
	}
	
	#endregion Declare Functions
	#region Declare Variables
	
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	$ConfigFilePath = "$ScriptDirectory\PowerLauncher_Config.ps1"
	
	. $ConfigFilePath
	
	$Log = "$ScriptDirectory\PowerLauncher.log"
	
	$AppVersion = "v1.2.0"
	
	#endregion Declare Variables#endregion Source: Globals.ps1

#region Source: PowerLauncher.psf
function Call-PowerLauncher_psf
{
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formPowerLauncher = New-Object 'System.Windows.Forms.Form'
	$tabControl1 = New-Object 'System.Windows.Forms.TabControl'
	$tabPg1 = New-Object 'System.Windows.Forms.TabPage'
	$flowPanelApps = New-Object 'System.Windows.Forms.FlowLayoutPanel'
	$btnCustom1 = New-Object 'System.Windows.Forms.Button'
	$btnCustom2 = New-Object 'System.Windows.Forms.Button'
	$btnCustom3 = New-Object 'System.Windows.Forms.Button'
	$btnCustom4 = New-Object 'System.Windows.Forms.Button'
	$btnCustom5 = New-Object 'System.Windows.Forms.Button'
	$btnCustom6 = New-Object 'System.Windows.Forms.Button'
	$btnCustom7 = New-Object 'System.Windows.Forms.Button'
	$btnCustom8 = New-Object 'System.Windows.Forms.Button'
	$btnCustom9 = New-Object 'System.Windows.Forms.Button'
	$btnCustom10 = New-Object 'System.Windows.Forms.Button'
	$tabPg2 = New-Object 'System.Windows.Forms.TabPage'
	$flowPanelDirs = New-Object 'System.Windows.Forms.FlowLayoutPanel'
	$btnCustom11 = New-Object 'System.Windows.Forms.Button'
	$btnCustom12 = New-Object 'System.Windows.Forms.Button'
	$btnCustom13 = New-Object 'System.Windows.Forms.Button'
	$btnCustom14 = New-Object 'System.Windows.Forms.Button'
	$btnCustom15 = New-Object 'System.Windows.Forms.Button'
	$btnCustom16 = New-Object 'System.Windows.Forms.Button'
	$btnCustom17 = New-Object 'System.Windows.Forms.Button'
	$btnCustom18 = New-Object 'System.Windows.Forms.Button'
	$btnCustom19 = New-Object 'System.Windows.Forms.Button'
	$btnCustom20 = New-Object 'System.Windows.Forms.Button'
	$menustrip1 = New-Object 'System.Windows.Forms.MenuStrip'
	$menuMenu = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuRestart = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuShutdown = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuExit = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuRefresh = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuTrouble = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuNetConnection = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$menuIP = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$aboutToolStripMenuItem = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$tooltip1 = New-Object 'System.Windows.Forms.ToolTip'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	$formPowerLauncher_Load = {
		Load-ConfigFileVariables
		Write-Output "[===== App Opened: $(logstamp) =====]" | Out-File $Log -Append
		Load-Buttons
		Tab-Title
	}
	
	$formPowerLauncher_Close = { Write-Output "[===== App Closed: $(logstamp) =====]" | Out-File $Log -Append }
	
	$btnCustom1_Click = { Button1-CustomFunction }
	$btnCustom2_Click = { Button2-CustomFunction }
	$btnCustom3_Click = { Button3-CustomFunction }
	$btnCustom4_Click = { Button4-CustomFunction }
	$btnCustom5_Click = { Button5-CustomFunction }
	$btnCustom6_Click = { Button6-CustomFunction }
	$btnCustom7_Click = { Button7-CustomFunction }
	$btnCustom8_Click = { Button8-CustomFunction }
	$btnCustom9_Click = { Button9-CustomFunction }
	$btnCustom10_Click = { Button10-CustomFunction }
	$btnCustom11_Click = { Button11-CustomFunction }
	$btnCustom12_Click = { Button12-CustomFunction }
	$btnCustom13_Click = { Button13-CustomFunction }
	$btnCustom14_Click = { Button14-CustomFunction }
	$btnCustom15_Click = { Button15-CustomFunction }
	$btnCustom16_Click = { Button16-CustomFunction }
	$btnCustom17_Click = { Button17-CustomFunction }
	$btnCustom18_Click = { Button18-CustomFunction }
	$btnCustom19_Click = { Button19-CustomFunction }
	$btnCustom20_Click = { Button20-CustomFunction }	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formPowerLauncher.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$btnCustom1.remove_Click($btnCustom1_Click)
			$btnCustom2.remove_Click($btnCustom2_Click)
			$btnCustom3.remove_Click($btnCustom3_Click)
			$btnCustom4.remove_Click($btnCustom4_Click)
			$btnCustom5.remove_Click($btnCustom5_Click)
			$btnCustom6.remove_Click($btnCustom6_Click)
			$btnCustom7.remove_Click($btnCustom7_Click)
			$btnCustom8.remove_Click($btnCustom8_Click)
			$btnCustom9.remove_Click($btnCustom9_Click)
			$btnCustom10.remove_Click($btnCustom10_Click)
			$btnCustom11.remove_Click($btnCustom11_Click)
			$btnCustom12.remove_Click($btnCustom12_Click)
			$btnCustom13.remove_Click($btnCustom13_Click)
			$btnCustom14.remove_Click($btnCustom14_Click)
			$btnCustom15.remove_Click($btnCustom15_Click)
			$btnCustom16.remove_Click($btnCustom16_Click)
			$btnCustom17.remove_Click($btnCustom17_Click)
			$btnCustom18.remove_Click($btnCustom18_Click)
			$btnCustom19.remove_Click($btnCustom19_Click)
			$btnCustom20.remove_Click($btnCustom20_Click)
			$formPowerLauncher.remove_FormClosed($formPowerLauncher_Close)
			$formPowerLauncher.remove_Load($formPowerLauncher_Load)
			$formPowerLauncher.remove_Load($Form_StateCorrection_Load)
			$formPowerLauncher.remove_Closing($Form_StoreValues_Closing)
			$formPowerLauncher.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formPowerLauncher.SuspendLayout()
	$tabControl1.SuspendLayout()
	$tabPg1.SuspendLayout()
	$flowPanelApps.SuspendLayout()
	$tabPg2.SuspendLayout()
	$flowPanelDirs.SuspendLayout()
	#
	# formPowerLauncher
	#
	$formPowerLauncher.Controls.Add($tabControl1)
	$formPowerLauncher.Controls.Add($menustrip1)
	$formPowerLauncher.AutoScroll = $True
	$formPowerLauncher.AutoSizeMode = 'GrowAndShrink'
	$formPowerLauncher.BackColor = 'White'
	$formPowerLauncher.ClientSize = '221, 567'
	#region Binary Data
	$formPowerLauncher.Icon = [System.Convert]::FromBase64String('
AAABAAIAICAAAAEAIACoEAAAJgAAAEBAAAABACAAKEIAAM4QAAAoAAAAIAAAAEAAAAABACAAAAAA
AIAQAAAAAAAAAAAAAAAAAAAAAAAAjEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+RTw//mFkc/5hZHP+YWRz/mFkc/5hZHP+YWRz/mFkc/5hZ
HP+YWRz/mFkc/5hZHP+SURH/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/xqSD
/59mLf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/8Shfv//////////////////////
/////////////////////////////////////82vkv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv/r39T//fz8/9jAqf+fZS3/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/xKF+////
////////////////////////////////////////////////////////za+S/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/+vf1P////////////39/P/XwKn/n2Ut/4xGAv+MRgL/
jEYC/4xGAv+vf1D/1Lqh/9S6of/UuqH/1Lqh/9S6of/UuqH/1Lqh/9S6of/UuqH/1Lqh/9S6of+1
iFz/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/2MCq//7+/v//////////////
///9/fz/18Cp/59lLf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
p3M//9/Muv/+/v3//////////////////f38/9jAqf+eYyr/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/6RuOP/cx7L//v38//////////////////38+//WvaX/nmMq
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+iaTL/2MGr//38+///
///////////////9/Pv/1r2l/55jK/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/n2Qs/9W8o//8+/r//////////////////fz7/9a9pf+eYyv/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5xgJv/Rtpz//Pr4//////////////////38
+//WvaX/nmMq/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+ZXCD/
zrGU//v49v/////////////////9+/r/1Lqh/5xhJ/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/l1gb/8usjv/+/f3//////////////////Pr5/5BODf+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+mcDv/5NXF//////////////////7+/v/l
1sf/jkoI/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+cYCX/2cGr//7+/f//////////
///////w59//tIZa/4xGA/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+UVBX/zK6Q//v6+P//
///////////////48+//wZx4/5BMCv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+PTAr/wJp1
//by7f/////////////////8+/r/z7OX/5ZWGP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RwT/tIZa/+/m3f/////////////////+/v7/3ci0/59lLP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/qHNA/+bXyP/+/v7/////////////////6dzQ/6t3Rv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/nWIo/9rFr//+/v7/////////////////8+zl/7iNZP+NSAX/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/lVUX/86xlP/8+/n/////////////////+vf0/8akgv+RTw7/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/o287//////////////////f38/9S6
oP+YWh3/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/+vf1P//////
/v7+/+HPvv+iajP/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/69/U/+zi1/+vf1D/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+wgFH/jkoI/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAEAAAACAAAAAAQAgAAAAAAAAQgAAAAAAAAAA
AAAAAAAAAAAAAIxGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+jbDb/pGw3/6RsN/+k
bDf/pGw3/6RsN/+kbDf/pGw3/6RsN/+kbDf/pGw3/6RsN/+kbDf/pGw3/6RsN/+kbDf/pGw3/6Rs
N/+kbDf/pGw3/6RsN/+kbDf/pGw3/6RsN/+PSwn/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/sIFS/5lcIP+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL//fz7////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////m18l
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/9jAqf/59vP/zbCT/5lbIP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC//38+///////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////5tfJf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/YwKn////////////5
9vP/zbCT/5lbH/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv/9/Pv/////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////+bXyX/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/2MCp///////////////////////69/T/za+S/5haHv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL//fz7////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////m18l/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/9jAqf//////////////
///////////////////69/T/za+T/5haHv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC//38+///////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////5tfJf+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv/YwKn////////////////////////////////////////////69/X/za+T
/5haHf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+pdUL/qnZE/6p2RP+qdkT/
qnZE/6p2RP+qdkT/qnZE/6p2RP+qdkT/qnZE/6p2RP+qdkT/qnZE/6p2RP+qdkT/qnZE/6p2RP+q
dkT/qnZE/6p2RP+qdkT/qnZE/6p2RP+QTAv/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/2MCp////////////////
///////////////////////////////////////6+Pb/zbCT/5haHv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/6dyP//i0cH//v39////////////////////////////////////////////
///////////6+PX/zbCT/5lbHv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/6h0Qf/fy7n/
/fz7///////////////////////////////////////////////////////69/T/zbCT/5lbH/+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/6VvOv/cx7P//fz6////////////////////////
///////////////////////////////69/T/yqqM/5dYG/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/6JqNP/Ywav//Pr5////////////////////////////////////////////////////
///49fH/yqqL/5dYG/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/6BmLv/VvKT/+/j2////
///////////////////////////////////////////////////49fH/yqqL/5dYG/+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/51iKf/St53/+fb0////////////////////////////////
///////////////////////49PD/yqqL/5dYHP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/5teI//Pspb/+PTw///////////////////////////////////////////////////////49PD/
yqqL/5dZHP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5hbHv/LrI7/9/Lu////////////
///////////////////////////////////////////48+//yqqL/5hZHP+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/5ZXGv/Ip4f/9fDr////////////////////////////////////////
///////////////48+//yqqL/5dZHP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5RUFf/F
oX//9O7o///////////////////////////////////////////////////////48+//yqqL/5dY
HP+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5JQEf/Bm3f/8+zl////////////////////
///////////////////////////////////49PD/yqqL/5dYG/+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/5FODf+9lnD/8Ojg////////////////////////////////////////////////
///////38u7/xqSE/5VUFv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5BMCv+6kWj/7+Xc
///////////////////////////////////////////////////////38u7/xqSD/5RUFf+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/45KCP+2i2D/7OHW////////////////////////////
//////////////////////7+/v/18Ov/lFMV/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/41IBf+2il///Pr5/////////////////////////////////////////////fv6/5dYG/+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGA/+sekn/6dzP////////////////////////
//////////////////////////z7+v+XWBr/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/6FoMf/e
y7j//v7+/////////////////////////////////////////////v7+/+vg1f+ufU7/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/mVsf/9K3nv/9+/r/////////////////////////////////////////
////////9O3n/7yUbf+OSQf/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+SUBD/xqSD//n18v//////////////
///////////////////////////////////69/T/yamK/5RTFP+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/49L
Cf+6kGj/8uvk//////////////////////////////////////////////////38+//Xv6j/nGAl
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jUcE/659Tf/q3dH//v7+////////////////////////////////
/////////////v79/+PTw/+ncT3/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/o2w2/9/Muv/+/v7/////
////////////////////////////////////////////7uTa/7OFWP+NSAX/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+aXiP/1Lqh//z7+f/////////////////////////////////////////////////28Ov/
wJt2/5FODf+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5RUFf/Ip4f/+PTx////////////////////////////
//////////////////////v49v/OsZT/llca/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/j0wK/7yTbP/z7OX/
/////////////////////////////////////////////////f38/9vFsP+fZS3/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+NSAT/sIFS/+vf1P/+/v7/////////////////////////////////////////////
////59nL/6p2Rf+MRwP/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+lbjn/4dC///79/f//////////////////
///////////////////////////////x6eH/t4xi/45JBv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/5tfJP/W
vqf//fz7//////////////////////////////////////////////////j18f/EoX//kk8P/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/lFMU/8qqi//69/X/////////////////////////////////////////
/////////fz7/9K3nf+YWh7/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+PSwn/vpZw//Xv6f/+/v7/////////
///////////////////////////////////+/v7/4M27/6JpM/+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
A/+xglT/7uPa//7+/v/////////////////////////////////////////////////s4Nb/rn1N
/4xHA/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/Nr5L/////////////////////////////////////
/////////////v7+//Tu6P+7kmr/jkkH/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/2MCp
////////////////////////////////////////////+vf0/8moif+TURL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/9jAqf/////////////////////////////////9/Pv/
17+o/5teI/+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/YwKn/
//////////////////////7+/f/j0sL/pnA8/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/2MCp/////////////////+7k2v+yhFf/jUcE/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/9jAqf//
////9fDr/8CZdf+QTQz/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv/UuaD/zbCT/5ZXGv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/klAQ/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xG
Av+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC
/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/
jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+M
RgL/jEYC/4xGAv+MRgL/jEYC/4xGAv+MRgL/jEYC/4xGAv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')
	#endregion
	$formPowerLauncher.MainMenuStrip = $menustrip1
	$formPowerLauncher.MaximizeBox = $False
	$formPowerLauncher.Name = "formPowerLauncher"
	$formPowerLauncher.StartPosition = 'CenterScreen'
	$formPowerLauncher.Text = "PowerLauncher"
	$formPowerLauncher.add_FormClosed($formPowerLauncher_Close)
	$formPowerLauncher.add_Load($formPowerLauncher_Load)
	#
	# tabControl1
	#
	$tabControl1.Controls.Add($tabPg1)
	$tabControl1.Controls.Add($tabPg2)
	$tabControl1.Dock = 'Fill'
	$tabControl1.Font = "Gadugi, 9.75pt"
	$tabControl1.Location = '0, 0'
	$tabControl1.Name = "tabControl1"
	$tabControl1.SelectedIndex = 0
	$tabControl1.Size = '221, 567'
	$tabControl1.TabIndex = 17
	#
	# tabPg1
	#
	$tabPg1.Controls.Add($flowPanelApps)
	$tabPg1.AutoScroll = $True
	$tabPg1.Font = "Gadugi, 9pt"
	$tabPg1.Location = '4, 25'
	$tabPg1.Name = "tabPg1"
	$tabPg1.Padding = '3, 3, 3, 3'
	$tabPg1.Size = '213, 538'
	$tabPg1.TabIndex = 0
	$tabPg1.Text = "Page 1"
	$tabPg1.UseVisualStyleBackColor = $True
	#
	# flowPanelApps
	#
	$flowPanelApps.Controls.Add($btnCustom1)
	$flowPanelApps.Controls.Add($btnCustom2)
	$flowPanelApps.Controls.Add($btnCustom3)
	$flowPanelApps.Controls.Add($btnCustom4)
	$flowPanelApps.Controls.Add($btnCustom5)
	$flowPanelApps.Controls.Add($btnCustom6)
	$flowPanelApps.Controls.Add($btnCustom7)
	$flowPanelApps.Controls.Add($btnCustom8)
	$flowPanelApps.Controls.Add($btnCustom9)
	$flowPanelApps.Controls.Add($btnCustom10)
	$flowPanelApps.AutoScroll = $True
	$flowPanelApps.Dock = 'Fill'
	$flowPanelApps.Location = '3, 3'
	$flowPanelApps.Name = "flowPanelApps"
	$flowPanelApps.Size = '207, 532'
	$flowPanelApps.TabIndex = 16
	#
	# btnCustom1
	#
	$btnCustom1.BackColor = 'ButtonFace'
	$btnCustom1.FlatAppearance.BorderColor = 'Gray'
	$btnCustom1.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom1.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom1.FlatStyle = 'Flat'
	$btnCustom1.Font = "Gadugi, 9.75pt"
	$btnCustom1.Location = '3, 3'
	$btnCustom1.Name = "btnCustom1"
	$btnCustom1.Size = '200, 47'
	$btnCustom1.TabIndex = 0
	$btnCustom1.Text = "Custom Button 1"
	$tooltip1.SetToolTip($btnCustom1, "Custom Button 1")
	$btnCustom1.UseVisualStyleBackColor = $False
	$btnCustom1.add_Click($btnCustom1_Click)
	#
	# btnCustom2
	#
	$btnCustom2.BackColor = 'ButtonFace'
	$btnCustom2.FlatAppearance.BorderColor = 'Gray'
	$btnCustom2.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom2.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom2.FlatStyle = 'Flat'
	$btnCustom2.Font = "Gadugi, 9.75pt"
	$btnCustom2.Location = '3, 56'
	$btnCustom2.Name = "btnCustom2"
	$btnCustom2.Size = '200, 47'
	$btnCustom2.TabIndex = 1
	$btnCustom2.Text = "Custom Button 2"
	$tooltip1.SetToolTip($btnCustom2, "Custom Button 2")
	$btnCustom2.UseVisualStyleBackColor = $False
	$btnCustom2.add_Click($btnCustom2_Click)
	#
	# btnCustom3
	#
	$btnCustom3.BackColor = 'ButtonFace'
	$btnCustom3.FlatAppearance.BorderColor = 'Gray'
	$btnCustom3.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom3.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom3.FlatStyle = 'Flat'
	$btnCustom3.Font = "Gadugi, 9.75pt"
	$btnCustom3.Location = '3, 109'
	$btnCustom3.Name = "btnCustom3"
	$btnCustom3.Size = '200, 47'
	$btnCustom3.TabIndex = 2
	$btnCustom3.Text = "Custom Button 3"
	$tooltip1.SetToolTip($btnCustom3, "Custom Button 3")
	$btnCustom3.UseVisualStyleBackColor = $False
	$btnCustom3.add_Click($btnCustom3_Click)
	#
	# btnCustom4
	#
	$btnCustom4.BackColor = 'ButtonFace'
	$btnCustom4.FlatAppearance.BorderColor = 'Gray'
	$btnCustom4.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom4.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom4.FlatStyle = 'Flat'
	$btnCustom4.Font = "Gadugi, 9.75pt"
	$btnCustom4.Location = '3, 162'
	$btnCustom4.Name = "btnCustom4"
	$btnCustom4.Size = '200, 47'
	$btnCustom4.TabIndex = 3
	$btnCustom4.Text = "Custom Button 4"
	$tooltip1.SetToolTip($btnCustom4, "Custom Button 4")
	$btnCustom4.UseVisualStyleBackColor = $False
	$btnCustom4.add_Click($btnCustom4_Click)
	#
	# btnCustom5
	#
	$btnCustom5.BackColor = 'ButtonFace'
	$btnCustom5.FlatAppearance.BorderColor = 'Gray'
	$btnCustom5.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom5.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom5.FlatStyle = 'Flat'
	$btnCustom5.Font = "Gadugi, 9.75pt"
	$btnCustom5.Location = '3, 215'
	$btnCustom5.Name = "btnCustom5"
	$btnCustom5.Size = '200, 47'
	$btnCustom5.TabIndex = 4
	$btnCustom5.Text = "Custom Button 5"
	$tooltip1.SetToolTip($btnCustom5, "Custom Button 5")
	$btnCustom5.UseVisualStyleBackColor = $False
	$btnCustom5.add_Click($btnCustom5_Click)
	#
	# btnCustom6
	#
	$btnCustom6.BackColor = 'ButtonFace'
	$btnCustom6.FlatAppearance.BorderColor = 'Gray'
	$btnCustom6.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom6.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom6.FlatStyle = 'Flat'
	$btnCustom6.Font = "Gadugi, 9.75pt"
	$btnCustom6.Location = '3, 268'
	$btnCustom6.Name = "btnCustom6"
	$btnCustom6.Size = '200, 47'
	$btnCustom6.TabIndex = 5
	$btnCustom6.Text = "Custom Button 6"
	$tooltip1.SetToolTip($btnCustom6, "Custom Button 6")
	$btnCustom6.UseVisualStyleBackColor = $False
	$btnCustom6.add_Click($btnCustom6_Click)
	#
	# btnCustom7
	#
	$btnCustom7.BackColor = 'ButtonFace'
	$btnCustom7.FlatAppearance.BorderColor = 'Gray'
	$btnCustom7.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom7.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom7.FlatStyle = 'Flat'
	$btnCustom7.Font = "Gadugi, 9.75pt"
	$btnCustom7.Location = '3, 321'
	$btnCustom7.Name = "btnCustom7"
	$btnCustom7.Size = '200, 47'
	$btnCustom7.TabIndex = 7
	$btnCustom7.Text = "Custom Button 7"
	$btnCustom7.UseVisualStyleBackColor = $False
	$btnCustom7.add_Click($btnCustom7_Click)
	#
	# btnCustom8
	#
	$btnCustom8.BackColor = 'ButtonFace'
	$btnCustom8.FlatAppearance.BorderColor = 'Gray'
	$btnCustom8.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom8.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom8.FlatStyle = 'Flat'
	$btnCustom8.Font = "Gadugi, 9.75pt"
	$btnCustom8.Location = '3, 374'
	$btnCustom8.Name = "btnCustom8"
	$btnCustom8.Size = '200, 47'
	$btnCustom8.TabIndex = 6
	$btnCustom8.Text = "Custom Button 8"
	$tooltip1.SetToolTip($btnCustom8, "Custom Button 7")
	$btnCustom8.UseVisualStyleBackColor = $False
	$btnCustom8.add_Click($btnCustom8_Click)
	#
	# btnCustom9
	#
	$btnCustom9.BackColor = 'ButtonFace'
	$btnCustom9.FlatAppearance.BorderColor = 'Gray'
	$btnCustom9.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom9.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom9.FlatStyle = 'Flat'
	$btnCustom9.Font = "Gadugi, 9.75pt"
	$btnCustom9.Location = '3, 427'
	$btnCustom9.Name = "btnCustom9"
	$btnCustom9.Size = '200, 47'
	$btnCustom9.TabIndex = 8
	$btnCustom9.Text = "Custom Button 9"
	$btnCustom9.UseVisualStyleBackColor = $False
	$btnCustom9.add_Click($btnCustom9_Click)
	#
	# btnCustom10
	#
	$btnCustom10.BackColor = 'ButtonFace'
	$btnCustom10.FlatAppearance.BorderColor = 'Gray'
	$btnCustom10.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom10.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom10.FlatStyle = 'Flat'
	$btnCustom10.Font = "Gadugi, 9.75pt"
	$btnCustom10.Location = '3, 480'
	$btnCustom10.Name = "btnCustom10"
	$btnCustom10.Size = '200, 47'
	$btnCustom10.TabIndex = 9
	$btnCustom10.Text = "Custom Button 10"
	$btnCustom10.UseVisualStyleBackColor = $False
	$btnCustom10.add_Click($btnCustom10_Click)
	#
	# tabPg2
	#
	$tabPg2.Controls.Add($flowPanelDirs)
	$tabPg2.AutoScroll = $True
	$tabPg2.Location = '4, 25'
	$tabPg2.Name = "tabPg2"
	$tabPg2.Padding = '3, 3, 3, 3'
	$tabPg2.Size = '213, 538'
	$tabPg2.TabIndex = 1
	$tabPg2.Text = "Page 2"
	$tabPg2.UseVisualStyleBackColor = $True
	#
	# flowPanelDirs
	#
	$flowPanelDirs.Controls.Add($btnCustom11)
	$flowPanelDirs.Controls.Add($btnCustom12)
	$flowPanelDirs.Controls.Add($btnCustom13)
	$flowPanelDirs.Controls.Add($btnCustom14)
	$flowPanelDirs.Controls.Add($btnCustom15)
	$flowPanelDirs.Controls.Add($btnCustom16)
	$flowPanelDirs.Controls.Add($btnCustom17)
	$flowPanelDirs.Controls.Add($btnCustom18)
	$flowPanelDirs.Controls.Add($btnCustom19)
	$flowPanelDirs.Controls.Add($btnCustom20)
	$flowPanelDirs.AutoScroll = $True
	$flowPanelDirs.Dock = 'Fill'
	$flowPanelDirs.Location = '3, 3'
	$flowPanelDirs.Name = "flowPanelDirs"
	$flowPanelDirs.Size = '207, 532'
	$flowPanelDirs.TabIndex = 17
	#
	# btnCustom11
	#
	$btnCustom11.BackColor = 'ButtonFace'
	$btnCustom11.FlatAppearance.BorderColor = 'Gray'
	$btnCustom11.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom11.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom11.FlatStyle = 'Flat'
	$btnCustom11.Font = "Gadugi, 9.75pt"
	$btnCustom11.Location = '3, 3'
	$btnCustom11.Name = "btnCustom11"
	$btnCustom11.Size = '200, 47'
	$btnCustom11.TabIndex = 13
	$btnCustom11.Text = "Custom Button 11"
	$btnCustom11.UseVisualStyleBackColor = $False
	$btnCustom11.add_Click($btnCustom11_Click)
	#
	# btnCustom12
	#
	$btnCustom12.BackColor = 'ButtonFace'
	$btnCustom12.FlatAppearance.BorderColor = 'Gray'
	$btnCustom12.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom12.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom12.FlatStyle = 'Flat'
	$btnCustom12.Font = "Gadugi, 9.75pt"
	$btnCustom12.Location = '3, 56'
	$btnCustom12.Name = "btnCustom12"
	$btnCustom12.Size = '200, 47'
	$btnCustom12.TabIndex = 14
	$btnCustom12.Text = "Custom Button 12"
	$btnCustom12.UseVisualStyleBackColor = $False
	$btnCustom12.add_Click($btnCustom12_Click)
	#
	# btnCustom13
	#
	$btnCustom13.BackColor = 'ButtonFace'
	$btnCustom13.FlatAppearance.BorderColor = 'Gray'
	$btnCustom13.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom13.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom13.FlatStyle = 'Flat'
	$btnCustom13.Font = "Gadugi, 9.75pt"
	$btnCustom13.Location = '3, 109'
	$btnCustom13.Name = "btnCustom13"
	$btnCustom13.Size = '200, 47'
	$btnCustom13.TabIndex = 15
	$btnCustom13.Text = "Custom Button 13"
	$btnCustom13.UseVisualStyleBackColor = $False
	$btnCustom13.add_Click($btnCustom13_Click)
	#
	# btnCustom14
	#
	$btnCustom14.BackColor = 'ButtonFace'
	$btnCustom14.FlatAppearance.BorderColor = 'Gray'
	$btnCustom14.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom14.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom14.FlatStyle = 'Flat'
	$btnCustom14.Font = "Gadugi, 9.75pt"
	$btnCustom14.Location = '3, 162'
	$btnCustom14.Name = "btnCustom14"
	$btnCustom14.Size = '200, 47'
	$btnCustom14.TabIndex = 16
	$btnCustom14.Text = "Custom Button 14"
	$btnCustom14.UseVisualStyleBackColor = $False
	$btnCustom14.add_Click($btnCustom14_Click)
	#
	# btnCustom15
	#
	$btnCustom15.BackColor = 'ButtonFace'
	$btnCustom15.FlatAppearance.BorderColor = 'Gray'
	$btnCustom15.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom15.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom15.FlatStyle = 'Flat'
	$btnCustom15.Font = "Gadugi, 9.75pt"
	$btnCustom15.Location = '3, 215'
	$btnCustom15.Name = "btnCustom15"
	$btnCustom15.Size = '200, 47'
	$btnCustom15.TabIndex = 17
	$btnCustom15.Text = "Custom Button 15"
	$btnCustom15.UseVisualStyleBackColor = $False
	$btnCustom15.add_Click($btnCustom15_Click)
	#
	# btnCustom16
	#
	$btnCustom16.BackColor = 'ButtonFace'
	$btnCustom16.FlatAppearance.BorderColor = 'Gray'
	$btnCustom16.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom16.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom16.FlatStyle = 'Flat'
	$btnCustom16.Font = "Gadugi, 9.75pt"
	$btnCustom16.Location = '3, 268'
	$btnCustom16.Name = "btnCustom16"
	$btnCustom16.Size = '200, 47'
	$btnCustom16.TabIndex = 18
	$btnCustom16.Text = "Custom Button 16"
	$btnCustom16.UseVisualStyleBackColor = $False
	$btnCustom16.add_Click($btnCustom16_Click)
	#
	# btnCustom17
	#
	$btnCustom17.BackColor = 'ButtonFace'
	$btnCustom17.FlatAppearance.BorderColor = 'Gray'
	$btnCustom17.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom17.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom17.FlatStyle = 'Flat'
	$btnCustom17.Font = "Gadugi, 9.75pt"
	$btnCustom17.Location = '3, 321'
	$btnCustom17.Name = "btnCustom17"
	$btnCustom17.Size = '200, 47'
	$btnCustom17.TabIndex = 19
	$btnCustom17.Text = "Custom Button 17"
	$btnCustom17.UseVisualStyleBackColor = $False
	$btnCustom17.add_Click($btnCustom17_Click)
	#
	# btnCustom18
	#
	$btnCustom18.BackColor = 'ButtonFace'
	$btnCustom18.FlatAppearance.BorderColor = 'Gray'
	$btnCustom18.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom18.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom18.FlatStyle = 'Flat'
	$btnCustom18.Font = "Gadugi, 9.75pt"
	$btnCustom18.Location = '3, 374'
	$btnCustom18.Name = "btnCustom18"
	$btnCustom18.Size = '200, 47'
	$btnCustom18.TabIndex = 20
	$btnCustom18.Text = "Custom Button 18"
	$btnCustom18.UseVisualStyleBackColor = $False
	$btnCustom18.add_Click($btnCustom18_Click)
	#
	# btnCustom19
	#
	$btnCustom19.BackColor = 'ButtonFace'
	$btnCustom19.FlatAppearance.BorderColor = 'Gray'
	$btnCustom19.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom19.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom19.FlatStyle = 'Flat'
	$btnCustom19.Font = "Gadugi, 9.75pt"
	$btnCustom19.Location = '3, 427'
	$btnCustom19.Name = "btnCustom19"
	$btnCustom19.Size = '200, 47'
	$btnCustom19.TabIndex = 21
	$btnCustom19.Text = "Custom Button 19"
	$btnCustom19.UseVisualStyleBackColor = $False
	$btnCustom19.add_Click($btnCustom19_Click)
	#
	# btnCustom20
	#
	$btnCustom20.BackColor = 'ButtonFace'
	$btnCustom20.FlatAppearance.BorderColor = 'Gray'
	$btnCustom20.FlatAppearance.MouseDownBackColor = 'BurlyWood'
	$btnCustom20.FlatAppearance.MouseOverBackColor = 'DarkSeaGreen'
	$btnCustom20.FlatStyle = 'Flat'
	$btnCustom20.Font = "Gadugi, 9.75pt"
	$btnCustom20.Location = '3, 480'
	$btnCustom20.Name = "btnCustom20"
	$btnCustom20.Size = '200, 47'
	$btnCustom20.TabIndex = 22
	$btnCustom20.Text = "Custom Button 20"
	$btnCustom20.UseVisualStyleBackColor = $False
	$btnCustom20.add_Click($btnCustom20_Click)
	#
	# menustrip1
	#
	[void]$menustrip1.Items.Add($menuMenu)
	[void]$menustrip1.Items.Add($menuRefresh)
	[void]$menustrip1.Items.Add($menuTrouble)
	$menustrip1.Location = '0, 0'
	$menustrip1.Name = "menustrip1"
	$menustrip1.Size = '427, 24'
	$menustrip1.TabIndex = 4
	$menustrip1.Text = "menustrip1"
	$menustrip1.Visible = $False
	#
	# menuMenu
	#
	[void]$menuMenu.DropDownItems.Add($menuRestart)
	[void]$menuMenu.DropDownItems.Add($menuShutdown)
	[void]$menuMenu.DropDownItems.Add($aboutToolStripMenuItem)
	[void]$menuMenu.DropDownItems.Add($menuExit)
	$menuMenu.Name = "menuMenu"
	$menuMenu.Size = '50, 20'
	$menuMenu.Text = "&Menu"
	#
	# menuRestart
	#
	$menuRestart.Name = "menuRestart"
	$menuRestart.Size = '185, 22'
	$menuRestart.Text = "&Restart Computer"
	#
	# menuShutdown
	#
	$menuShutdown.Name = "menuShutdown"
	$menuShutdown.Size = '185, 22'
	$menuShutdown.Text = "&Shutdown Computer"
	#
	# menuExit
	#
	$menuExit.Name = "menuExit"
	$menuExit.Size = '185, 22'
	$menuExit.Text = "&Exit"
	#
	# menuRefresh
	#
	$menuRefresh.Name = "menuRefresh"
	$menuRefresh.Size = '117, 20'
	$menuRefresh.Text = "&Check Connection"
	#
	# menuTrouble
	#
	[void]$menuTrouble.DropDownItems.Add($menuNetConnection)
	[void]$menuTrouble.DropDownItems.Add($menuIP)
	$menuTrouble.Name = "menuTrouble"
	$menuTrouble.Size = '90, 20'
	$menuTrouble.Text = "&Troubleshoot"
	#
	# menuNetConnection
	#
	$menuNetConnection.Name = "menuNetConnection"
	$menuNetConnection.Size = '184, 22'
	$menuNetConnection.Text = "Network Connection"
	#
	# menuIP
	#
	$menuIP.Name = "menuIP"
	$menuIP.Size = '184, 22'
	$menuIP.Text = "Show IP Address"
	#
	# aboutToolStripMenuItem
	#
	$aboutToolStripMenuItem.Name = "aboutToolStripMenuItem"
	$aboutToolStripMenuItem.Size = '185, 22'
	$aboutToolStripMenuItem.Text = "About"
	#
	# tooltip1
	#
	$flowPanelDirs.ResumeLayout()
	$tabPg2.ResumeLayout()
	$flowPanelApps.ResumeLayout()
	$tabPg1.ResumeLayout()
	$tabControl1.ResumeLayout()
	$formPowerLauncher.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formPowerLauncher.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formPowerLauncher.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formPowerLauncher.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formPowerLauncher.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formPowerLauncher.ShowDialog()
}
#endregion Source: PowerLauncher.psf

#Start the application
Main ($CommandLine)
